apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "stable-diffusion.fullname" . }}
  labels:
    {{- include "stable-diffusion.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "stable-diffusion.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stable-diffusion.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "stable-diffusion.fullname" . }}-model-store
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- with .Values.persistence.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stable-diffusion.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stable-diffusion.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: ensure-stable-models
          image: {{ .Values.init.image }}
          command:
            - /init.sh
          volumeMounts:
            - mountPath: /models
              name: {{ include "stable-diffusion.fullname" . }}-model-store
            - mountPath:  /init.sh
              subPath:    {{ .Values.init.downloadMethod }}-init.sh
              name:       init
              readOnly:   true
      containers:
        - name: {{ .Chart.Name }}-stable-diffusion
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "stable-diffusion.fullname" . }}-config
          ports:
            - name: http
              containerPort: 7860
              protocol: TCP
          volumeMounts:
            - mountPath: /models
              name: {{ include "stable-diffusion.fullname" . }}-model-store
          # Todo - Implement an efficient readiness and liveness check
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        volumes:
          - name: init
            configMap:
              name: {{ include "stable-diffusion.fullname" . }}-init-config
              defaultMode: 0555
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
